name: OS-1 Oscilloscope Project
baseurl: /os

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

gems:
  - jekyll-last-modified-at
